### ISSUE TITLE
Correct the letter p from uppercase to lowercase

### ISSUE THREAD

**Issue by mre1ght** [scheme-dojo/scheme-dojo.github.io#17]
### Current Situation
` <P class="version-tag">v1.0.0</P>`

### Ideal Situation
` <p class="version-tag">v1.0.0</p>`

**Comment by rhmtrz** [comment]
@mre1ght  

This kind of problem is better to mention when reviewing the source code. 

In case of making an issue, it is better to add the  address and references 

Please add the location of this typo problem.  which file and what line of code
