### ISSUE TITLE
Implement function to toggle display when button is pressed

### ISSUE THREAD

**Issue by mre1ght** [scheme-dojo/scheme-dojo.github.io#18]
### Current Situation
The display is toggled using `input` and `label `tags.

### Ideal Situation
Implement the display toggle functionality using JavaScript.

### Reason
The functionality to toggle display by pressing a button will be frequently used in the future.
Let's learn how to use it for study purposes.

### Reference
https://www.pyxofy.com/how-to-toggle-display-with-javascript/

**Comment by rhmtrz** [comment]
@mre1ght  

If this method is used, the structure will be changed.  It required refactoring. let's do this in the next version of the app.
