### ISSUE TITLE
Implement Menu and Close icons

### ISSUE THREAD

**Issue by mre1ght** [scheme-dojo/scheme-dojo.github.io#19]
### Current Situation
The HTML code for the hamburger icon and the cancel button is not unified.

### Ideal Situation
Decide on one icon provider site and use it consistently.

### Reason
To improve the appearance of the code.

### Reference
There are various icon provider sites, but Google appears first in search results, so let's use this one:
https://fonts.google.com/icons?icon.size=24&icon.color=%235f6368
<img width="256" alt="スクリーンショット 2024-07-12 12 13 22" src="https://github.com/user-attachments/assets/28e6f977-a8bc-4bb6-84e5-1264ffa8f770">

For actual usage, please refer to the following site:
https://icon-design.jp/news/how-to-use-google-material-icons/

#### ※But, If you like the site that got the `fas fa-bars burger-icon`, that site is fine too.

**Comment by rhmtrz** [comment]
@mre1ght  

After refactoring the toggle menu issue #18 , then fix this issue.
