### ISSUE TITLE
Changing class and id names

### ISSUE THREAD

**Issue by mre1ght** [scheme-dojo/scheme-dojo.github.io#6]
I missed it in yesterday's review. sorry.

1. Change the id name from `answer-btn `to` enter-btn`
2. Unify the class name and id name. （Please correct any other mismatches between the class name and ID name.）

#### Before (Just an example)
```
        <input class="input" id="input-tag" type="text" placeholder="Input your answer and then press enter button" /> 
        <button class="input" id="answer-btn" >Enter</button>
```

#### After
```
        <input class="input-tag" id="input-tag" type="text" placeholder="Input your answer and then press enter button" /> 
        <button class="enter-btn" id="enter-btn" >Enter</button>
```

**Comment by rhmtrz** [comment]
@rabiarz  

Please read the below article on how to choose a name for the class of HTML tags. 

https://medium.com/@erennaktas/how-should-class-naming-be-in-html-clean-code-8703425a1c3e
